### PR TITLE
Session

### PR DESCRIPTION
**Pull request by crccw**
[Review on Reviewable](https://reviewable.io/reviews/bnuacm/bnuoj-web-v4-rails/6)

### CODE REVIEW

**Comment by 51isoft** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/6)

---

I don't think it's true:
https://stackoverflow.com/questions/5860950/setting-session-timeout-in-rails-3

Even it's true, you can still add a last_login field. Using DB is an overkill.

---

<sup>**[app/assets/javascripts/application.js, line 16 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/6#-Jk3acqbuW-NpQ6-Vq17)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/b133312f3480e7a541c3daf002624ac6bd4b6040/app/assets/javascripts/application.js#L16)):</sup>
Don't use turbolinks yet

---

<sup>**[app/assets/javascripts/templates/dialogs/login_box.jst.hbs, line 7 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/6#-Jk3agLnTJC9m3orvZ1o)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/b133312f3480e7a541c3daf002624ac6bd4b6040/app/assets/javascripts/templates/dialogs/login_box.jst.hbs#L7)):</sup>
why would you change the path?

---

<sup>**[app/assets/javascripts/templates/dialogs/login_box.jst.hbs, line 11 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/6#-Jk3ajejXKRkKS-oqckr)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/b133312f3480e7a541c3daf002624ac6bd4b6040/app/assets/javascripts/templates/dialogs/login_box.jst.hbs#L11)):</sup>
Use a more sensible name please.

---

<sup>**[app/controllers/application_controller.rb, line 53 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/6#-Jk3b4qld9Wkt7pRkrdM)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/b133312f3480e7a541c3daf002624ac6bd4b6040/app/controllers/application_controller.rb#L53)):</sup>
No, we don't need to check ip.

---

<sup>**[app/controllers/sessions_controller.rb, line 1 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/6#-Jk3bCKISG6NC55kYm55)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/b133312f3480e7a541c3daf002624ac6bd4b6040/app/controllers/sessions_controller.rb#L1)):</sup>
Remove

---

<sup>**[app/models/session.rb, line 1 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/6#-Jk3bETm0YlvA_oARpJf)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/b133312f3480e7a541c3daf002624ac6bd4b6040/app/models/session.rb#L1)):</sup>
Ditto

---

<sup>**[app/models/user.rb, line 16 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/6#-Jk3bFbL3s9A-_5Wmh8X)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/b133312f3480e7a541c3daf002624ac6bd4b6040/app/models/user.rb#L16)):</sup>
Ditto

---

<sup>**[app/views/layouts/_navbar.html.erb, line 122 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/6#-Jk3bHHX0MZ7XJGFFdsS)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/b133312f3480e7a541c3daf002624ac6bd4b6040/app/views/layouts/_navbar.html.erb#L122)):</sup>
Ditto

---

<sup>**[app/views/layouts/application.html.erb, line 21 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/6#-Jk3bJjG2PC3UDSIyLa6)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/b133312f3480e7a541c3daf002624ac6bd4b6040/app/views/layouts/application.html.erb#L21)):</sup>
Don't use it yet, we have ajax navigation that could potentially cause the conflict.

---

<sup>**[bower.json, line 12 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/6#-Jk3bVabeI-x7bsYte31)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/b133312f3480e7a541c3daf002624ac6bd4b6040/bower.json#L12)):</sup>
ditto

---

<sup>**[config/initializers/session_store.rb, line 4 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/6#-Jk3bbYP4P92cZL126fw)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/b133312f3480e7a541c3daf002624ac6bd4b6040/config/initializers/session_store.rb#L4)):</sup>
We can store this for Max time

---

<sup>**[config/routes.rb, line 20 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/6#-Jk3bjs69Z9GL4rCBUT5)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/b133312f3480e7a541c3daf002624ac6bd4b6040/config/routes.rb#L20)):</sup>
ditto

---

**Comment by crccw** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/6)

---

You can set the expire time, but you can't dynamically set it. So if a expire date is set, user will always be remembered; if not set, always not remebered. Session may not be a good choice here.

---

<sup>**[app/assets/javascripts/application.js, line 16 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/6#-Jk3acqbuW-NpQ6-Vq17)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/b133312f3480e7a541c3daf002624ac6bd4b6040/app/assets/javascripts/application.js#L16)):</sup>
but use GET to logout is inappopriate...shouldn't we be RESTful?

---

<sup>**[app/assets/javascripts/templates/dialogs/login_box.jst.hbs, line 7 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/6#-Jk3agLnTJC9m3orvZ1o)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/b133312f3480e7a541c3daf002624ac6bd4b6040/app/assets/javascripts/templates/dialogs/login_box.jst.hbs#L7)):</sup>
huh... I've read an article which goes there should be nouns in RESTful url...

---

<sup>**[app/controllers/application_controller.rb, line 53 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/6#-Jk3b4qld9Wkt7pRkrdM)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/b133312f3480e7a541c3daf002624ac6bd4b6040/app/controllers/application_controller.rb#L53)):</sup>
So session fixation attack is still possible

---

**Comment by 51isoft** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/6)

---

Yes, but you can check last login time. And set session for always remember.

---

<sup>**[app/assets/javascripts/application.js, line 16 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/6#-Jk3acqbuW-NpQ6-Vq17)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/b133312f3480e7a541c3daf002624ac6bd4b6040/app/assets/javascripts/application.js#L16)):</sup>
You can change it to post. Why do we need turbolink to do it?

---

<sup>**[app/assets/javascripts/templates/dialogs/login_box.jst.hbs, line 7 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/6#-Jk3agLnTJC9m3orvZ1o)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/b133312f3480e7a541c3daf002624ac6bd4b6040/app/assets/javascripts/templates/dialogs/login_box.jst.hbs#L7)):</sup>
Point it out. RESTful should also be meaningful.

---

<sup>**[app/controllers/application_controller.rb, line 53 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/6#-Jk3b4qld9Wkt7pRkrdM)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/b133312f3480e7a541c3daf002624ac6bd4b6040/app/controllers/application_controller.rb#L53)):</sup>
I remember the credential in my computer, not on an IP. By checking IP, this function is basically useless.

---

**Comment by crccw** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/6)

---

So if the user don't want to be remembered, how to determine whether the session is still valid or not?

---

<sup>**[app/controllers/application_controller.rb, line 53 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/6#-Jk3b4qld9Wkt7pRkrdM)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/b133312f3480e7a541c3daf002624ac6bd4b6040/app/controllers/application_controller.rb#L53)):</sup>
huh..Right..
But what about security... is there something to identify the client? canvas fingerprints?

---

**Comment by crccw** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/6)

---

<sup>**[app/assets/javascripts/templates/dialogs/login_box.jst.hbs, line 7 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/6#-Jk3agLnTJC9m3orvZ1o)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/b133312f3480e7a541c3daf002624ac6bd4b6040/app/assets/javascripts/templates/dialogs/login_box.jst.hbs#L7)):</sup>
http://www.restapitutorial.com/lessons/restfulresourcenaming.html

---

**Comment by 51isoft** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/6)

---

per discussion earlier. we might not need this pr any more :(

---

<sup>**[app/assets/javascripts/templates/dialogs/login_box.jst.hbs, line 7 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/6#-Jk3agLnTJC9m3orvZ1o)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/b133312f3480e7a541c3daf002624ac6bd4b6040/app/assets/javascripts/templates/dialogs/login_box.jst.hbs#L7)):</sup>
I think /login ort

---

**Pull request closed without merging**
