### PR TITLE
I18n in js

### PR DESCRIPTION
**Pull request by crccw**
1. update i18n-js to 3.0.0rc8
2. provide a t helper for hbs

[Review on Reviewable](https://reviewable.io/reviews/bnuacm/bnuoj-web-v4-rails/5)

### CODE REVIEW

**Comment by 51isoft** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/5)

---

<sup>**[app/assets/javascripts/templates/dialogs/source_code_box.jst.hbs, line 12 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/5#-Jji2UUg2-nOfbz8pZCT)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/a4e69821f2916f34be9afb158c033f5c73dab271/app/assets/javascripts/templates/dialogs/source_code_box.jst.hbs#L12)):</sup>
This contains HTML tag right?

---

<sup>**[app/assets/javascripts/views/contest_list_view.js, line 169 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/5#-Jji2lKaXlPJiUP4Kxzu)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/a4e69821f2916f34be9afb158c033f5c73dab271/app/assets/javascripts/views/contest_list_view.js#L169)):</sup>
Really? data is from DB

---

<sup>**[app/assets/javascripts/views/contest_list_view.js, line 182 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/5#-Jji2qLLDcdfehpMbmBB)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/a4e69821f2916f34be9afb158c033f5c73dab271/app/assets/javascripts/views/contest_list_view.js#L182)):</sup>
ditto

---

<sup>**[app/assets/javascripts/views/problem_list_view.js, line 227 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/5#-Jji2uugiHgmET-9Y2t7)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/a4e69821f2916f34be9afb158c033f5c73dab271/app/assets/javascripts/views/problem_list_view.js#L227)):</sup>
ditto

---

<sup>**[app/assets/javascripts/views/status_list_view.js, line 226 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/5#-Jji33jPelz1aCpNEZ3j)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/a4e69821f2916f34be9afb158c033f5c73dab271/app/assets/javascripts/views/status_list_view.js#L226)):</sup>
ditto

---

**Comment by crccw** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/5)

---

<sup>**[app/assets/javascripts/templates/dialogs/source_code_box.jst.hbs, line 12 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/5#-Jji2UUg2-nOfbz8pZCT)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/a4e69821f2916f34be9afb158c033f5c73dab271/app/assets/javascripts/templates/dialogs/source_code_box.jst.hbs#L12)):</sup>
Done.

---

<sup>**[app/assets/javascripts/views/contest_list_view.js, line 169 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/5#-Jji2lKaXlPJiUP4Kxzu)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/a4e69821f2916f34be9afb158c033f5c73dab271/app/assets/javascripts/views/contest_list_view.js#L169)):</sup>
Done.

---

<sup>**[app/assets/javascripts/views/contest_list_view.js, line 182 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/5#-Jji2qLLDcdfehpMbmBB)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/a4e69821f2916f34be9afb158c033f5c73dab271/app/assets/javascripts/views/contest_list_view.js#L182)):</sup>
Done.

---

<sup>**[app/assets/javascripts/views/problem_list_view.js, line 227 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/5#-Jji2uugiHgmET-9Y2t7)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/a4e69821f2916f34be9afb158c033f5c73dab271/app/assets/javascripts/views/problem_list_view.js#L227)):</sup>
Done.

---

<sup>**[app/assets/javascripts/views/status_list_view.js, line 226 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/5#-Jji33jPelz1aCpNEZ3j)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/a4e69821f2916f34be9afb158c033f5c73dab271/app/assets/javascripts/views/status_list_view.js#L226)):</sup>
Done.

---

**Comment by 51isoft** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/5)

---

<sup>**[app/assets/javascripts/templates/dialogs/source_code_box.jst.hbs, line 12 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/5#-Jji2UUg2-nOfbz8pZCT)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/a4e69821f2916f34be9afb158c033f5c73dab271/app/assets/javascripts/templates/dialogs/source_code_box.jst.hbs#L12)):</sup>
Hmmm, result should use {{{, since we are wrapping it with <span> right?

---

**Comment by crccw** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/5)

---

<sup>**[app/assets/javascripts/templates/dialogs/source_code_box.jst.hbs, line 12 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/5#-Jji2UUg2-nOfbz8pZCT)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/a4e69821f2916f34be9afb158c033f5c73dab271/app/assets/javascripts/templates/dialogs/source_code_box.jst.hbs#L12)):</sup>
Done.

---

**Pull request merged**
