### PR TITLE
A more flexible privilege mechanism

### PR DESCRIPTION
**Pull request by crccw**
Each user and usergroup will have several privileges like"edit_contest_info", "access_admin_panel", "crawl_single_problem", "crawl_mass_problem" and so on. Privileges can come with restrictions like { "id" => "534 }, { "vname" => "PKU"  }, if an action meet ANY of the restrictions it will be granted.

Access control effects in controllers, models and views:
  In controllers, both has_priv and require_priv are provided, the former one will return a bool value and executes the block given if action is granted, will enables to apply different logic to different users; the latter one will raise Authorization::NotAuthorized if action is denied, enforcing some kind of restrictions.
  In models, only require_priv is provided, which should be used to check certain action is approved or not, in case controllers fail to do that.
  In views, only has_priv is provided to display different content accordingly.

Problems I have now is performance concern and back compatibility, the latter one could be solved by dynamically granting permissions to current_user, which is not very elegent though.

[Review on Reviewable](https://reviewable.io/reviews/bnuacm/bnuoj-web-v4-rails/3)

### CODE REVIEW

**Comment by 51isoft** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/3)

---

<sup>**[app/models/concerns/privileged.rb, line 1 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/3#-Ji_lByrrJo4n8j7Sf3-)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/362fb988c2f957a1c66be1c6ed6f68903dda775c/app/models/concerns/privileged.rb#L1)):</sup>
I see no advantage of injecting this to every method. It'll slow down the performance drastically.

---

<sup>**[app/models/user.rb, line 44 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/3#-Ji_lV34Swidz5VAxb23)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/362fb988c2f957a1c66be1c6ed6f68903dda775c/app/models/user.rb#L44)):</sup>
Let's just use before filter

---

<sup>**[db/migrate/20150218060735_create_privileges.rb, line 1 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/3#-Ji_lap1JIhMk08MwQOi)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/362fb988c2f957a1c66be1c6ed6f68903dda775c/db/migrate/20150218060735_create_privileges.rb#L1)):</sup>
Just heads up, we might probably migrate contest user db afterwards.

---

<sup>**[db/migrate/20150218060953_create_user_groups.rb, line 1 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/3#-Ji_luPJ1r8G1d5E9iIc)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/362fb988c2f957a1c66be1c6ed6f68903dda775c/db/migrate/20150218060953_create_user_groups.rb#L1)):</sup>
What's the usage of this table? I can't see it. You are not creating group permissions right?

---

**Comment by crccw** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/3)

---

<sup>**[app/models/concerns/privileged.rb, line 0 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/3#-Ji_lByrrJo4n8j7Sf3-)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/362fb988c2f957a1c66be1c6ed6f68903dda775c/app/models/concerns/privileged.rb#L0)):</sup>
Done.

---

<sup>**[app/models/user.rb, line 46 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/3#-Ji_lV34Swidz5VAxb23)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/362fb988c2f957a1c66be1c6ed6f68903dda775c/app/models/user.rb#L46)):</sup>
Done.

---

<sup>**[db/migrate/20150218060735_create_privileges.rb, line 1 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/3#-Ji_lap1JIhMk08MwQOi)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/362fb988c2f957a1c66be1c6ed6f68903dda775c/db/migrate/20150218060735_create_privileges.rb#L1)):</sup>
Done.

---

<sup>**[db/migrate/20150218060953_create_user_groups.rb, line 0 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/3#-Ji_luPJ1r8G1d5E9iIc)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/362fb988c2f957a1c66be1c6ed6f68903dda775c/db/migrate/20150218060953_create_user_groups.rb#L0)):</sup>
Done.

---

**Comment by 51isoft** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/3)

---

<sup>**[app/controllers/application_controller.rb, line 39 [r2]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/3#-JijJwim8pUboEASZz4O)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/ac63760030e730e5a332fc3d90869cadf683f5b4/app/controllers/application_controller.rb#L39)):</sup>
Add params for redirect after login, also error message to be displayed on that page?

---

<sup>**[app/controllers/application_controller.rb, line 47 [r2]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/3#-JijK6cacTa3CMc2RIbc)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/ac63760030e730e5a332fc3d90869cadf683f5b4/app/controllers/application_controller.rb#L47)):</sup>
Consider create a user-friendly error page?

---

<sup>**[app/helpers/access_helper.rb, line 1 [r2]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/3#-JijLrJ4cDxtHQd6oFeA)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/ac63760030e730e5a332fc3d90869cadf683f5b4/app/helpers/access_helper.rb#L1)):</sup>
I don't think we need access helper, just do it in application helper.
There's a good discussion about what goes to where: https://stackoverflow.com/questions/60658/rails-model-view-controller-and-helper-what-goes-where

---

<sup>**[app/helpers/access_helper.rb, line 2 [r2]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/3#-JijGasr4rPSjiAHNoLm)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/ac63760030e730e5a332fc3d90869cadf683f5b4/app/helpers/access_helper.rb#L2)):</sup>
I don't think we need a helper function to raise an exception. Just do it in place, it'll make code much easier to read.

---

<sup>**[app/helpers/access_helper.rb, line 12 [r2]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/3#-JijLO8iGRrzHKUUhpHk)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/ac63760030e730e5a332fc3d90869cadf683f5b4/app/helpers/access_helper.rb#L12)):</sup>
Hmm, never seen $_ syntax before, any docs?

---

<sup>**[db/schema.rb, line 158 [r2]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/3#-JijJ6YUWQs7crjo9tb4)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/ac63760030e730e5a332fc3d90869cadf683f5b4/db/schema.rb#L158)):</sup>
Index is not right. There's no need to create index for each of them. You'll only need a four field key.

---

**Comment by crccw** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/3)

---

<sup>**[app/controllers/application_controller.rb, line 39 [r2]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/3#-JijJwim8pUboEASZz4O)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/ac63760030e730e5a332fc3d90869cadf683f5b4/app/controllers/application_controller.rb#L39)):</sup>
Done.

---

<sup>**[app/controllers/application_controller.rb, line 47 [r2]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/3#-JijK6cacTa3CMc2RIbc)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/ac63760030e730e5a332fc3d90869cadf683f5b4/app/controllers/application_controller.rb#L47)):</sup>
normally users should never reach here, since we do not expose links/options which they don't have access to.

---

<sup>**[app/helpers/access_helper.rb, line 1 [r2]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/3#-JijLrJ4cDxtHQd6oFeA)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/ac63760030e730e5a332fc3d90869cadf683f5b4/app/helpers/access_helper.rb#L1)):</sup>
Done.

---

<sup>**[app/helpers/access_helper.rb, line 2 [r2]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/3#-JijGasr4rPSjiAHNoLm)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/ac63760030e730e5a332fc3d90869cadf683f5b4/app/helpers/access_helper.rb#L2)):</sup>
Done.

---

<sup>**[app/helpers/access_helper.rb, line 12 [r2]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/3#-JijLO8iGRrzHKUUhpHk)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/ac63760030e730e5a332fc3d90869cadf683f5b4/app/helpers/access_helper.rb#L12)):</sup>
Done.

---

<sup>**[db/schema.rb, line 158 [r2]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/3#-JijJ6YUWQs7crjo9tb4)** ([raw file](https://github.com/bnuacm/bnuoj-web-v4-rails/blob/ac63760030e730e5a332fc3d90869cadf683f5b4/db/schema.rb#L158)):</sup>
Done.

---

**Comment by 51isoft** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v4-rails/3)

---

**Pull request merged**
